### ISSUE TITLE
Example project no longer working

### ISSUE THREAD

**Issue by kevgathuku** [ervinb/docker-compose-example#1]
While following the guides on [Testing multi-container applications with Docker Compose and Semaphore](https://semaphoreci.com/docs/docker/testing-multicontainer-apps-with-docker-compose-and-semaphore.html) I ran into this issue:

```bash
$ docker-compose run web rake db:create
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
```
(See full trace by running task with --trace)

It seems the command is not run inside the `myapp` working directory by default.

**Comment by ervinb** [comment]
Hi @kevgathuku!

The repository has been moved [here](https://github.com/renderedtext/docker-compose-example). We also updated all the relevant links in the docs. Thanks for reporting the problem!
